version: "3.9"
services:
    database:
        image: postgres
        networks:
            - backend
        env_file: database.env
        volumes:
            - microcentral:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        build: ./backend
        image: microcentral_backend:latest
        command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend:/app
        networks:
            - backend
        depends_on:
            - database
        env_file: app.env
        ports:
            - "8000:8000"

    frontend:
        build: ./frontend
        image: microcentral_frontend:latest
        command: npm run dev -- --host
        volumes:
            - ./frontend:/app
        networks:
            - backend
        depends_on:
            - backend
        ports:
            - "5173:5173"

networks:
    backend:
        driver: bridge

volumes:
    microcentral:
        driver: local
