version: "3.9"
services:
    database:
        image: postgres
        networks:
            - backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=microcentral
        ports:
            - "5432:5432"

    app:
        build: .
        image: microcentral:latest
        command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/usr/src/app
        networks:
            - backend
        depends_on:
            - database
        env_file: .env
        ports:
            - "8000:8000"

networks:
    backend:
        driver: bridge

