version: "3"
services:
    database:
        image: postgres
        networks:
            - backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=microcentral
        ports:
            - "5432:5432"

    backend:
        profiles:   # will start only if `docker-compose --profile prod up` is used
            - prod
        image: noraali/backend:${TAG}
        command: alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/usr/src/app
        networks:
            - backend
        depends_on:
            - database
        env_file: .env
        ports:
            - "8000:8000"

    # runs on http://localhost:9000/?pgsql=database&username=postgres&db=microcentral&ns=public
    adminer:
        image: adminer
        networks:
            - backend
        ports:
            - "9000:8080"
        depends_on:
            - database
        environment:
            - ADMINER_DEFAULT_SERVER=database
    
    frontend:
        image: noraali/frontend:${TAG}
        depends_on:
            - backend
            - database
        env_file: .env
        ports:
            - "3000:3000" 


networks:
    backend:
        driver: bridge

