version: "3"
services:
    oauth2-proxy:
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        environment:
        - OAUTH2_PROXY_PROVIDER=github
        - OAUTH2_PROXY_CLIENT_ID=Ov23liMXhvKZLUvSgRaL
        - OAUTH2_PROXY_CLIENT_SECRET=2de1a16e3ffd65224ea01691ccb0c5b2ac76d12d
        - OAUTH2_PROXY_COOKIE_SECRET=mY1hDibXMr0fvi9KdXFbKMAWd2ojgfLn
        - OAUTH2_PROXY_COOKIE_SECURE=false
        - OAUTH2_PROXY_EMAIL_DOMAINS=*
        - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback  
        - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
        - OAUTH2_PROXY_UPSTREAMS=http://localhost:3000
        - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true        # Pass access token to upstream
        - OAUTH2_PROXY_COOKIE_EXPIRE=20s   # Set to 0 to create a session cookie
        # - OAUTH2_PROXY_COOKIE_DOMAIN="http://localhost:4180"
        - OAUTH2_PROXY_LOG_LEVEL=debug    # Enable debug logging for more information
        # - OAUTH2_PROXY_COOKIE_REFRESH= 0s  # cookie refresh
        - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true         # Set Authorization header
        - OAUTH2_PROXY_SET_XAUTHREQUEST=true                 # Set X-Auth-Request headers
        
        ports:
        - "4180:4180"
        networks:
        - backend

    database:
        image: postgres
        networks:
            - backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=microcentral
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        profiles:   # will start only if `docker-compose --profile prod up` is used
            - prod
        image: noraali/backend:${TAG}
        command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/usr/src/app
        networks:
            - backend
        depends_on:
            - database
            - oauth2-proxy
        env_file: .env
        ports:
            - "8000:8000"

    # runs on http://localhost:9000/?pgsql=database&username=postgres&db=microcentral&ns=public
    adminer:
        image: adminer
        networks:
            - backend
        ports:
            - "9000:8080"
        depends_on:
            - database
        environment:
            - ADMINER_DEFAULT_SERVER=database
    
    frontend:
        image: noraali/frontend:${TAG}
        depends_on:
            - backend
            - database
            - oauth2-proxy
        env_file: .env
        ports:
            - "3000:3000" 
    

networks:
    backend:
        driver: bridge

volumes:
    postgres_data: