"""Init

Revision ID: ee005e022621
Revises: 
Create Date: 2022-10-06 21:30:27.167370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee005e022621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('integer', 'boolean', name='type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_code'), 'metric', ['code'], unique=True)
    op.create_index(op.f('ix_metric_id'), 'metric', ['id'], unique=False)
    op.create_index(op.f('ix_metric_name'), 'metric', ['name'], unique=True)
    op.create_table('microservicescorecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microserviceId', sa.Integer(), nullable=False),
    sa.Column('scorecardId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microservicescorecard_id'), 'microservicescorecard', ['id'], unique=False)
    op.create_table('scorecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecard_id'), 'scorecard', ['id'], unique=False)
    op.create_table('scorecardmetrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scorecardId', sa.Integer(), nullable=False),
    sa.Column('metricId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecardmetrics_id'), 'scorecardmetrics', ['id'], unique=False)
    op.create_table('servicemetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.Column('metricId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicemetric_id'), 'servicemetric', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('microservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('teamId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microservice_id'), 'microservice', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microservice_id'), table_name='microservice')
    op.drop_table('microservice')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_servicemetric_id'), table_name='servicemetric')
    op.drop_table('servicemetric')
    op.drop_index(op.f('ix_scorecardmetrics_id'), table_name='scorecardmetrics')
    op.drop_table('scorecardmetrics')
    op.drop_index(op.f('ix_scorecard_id'), table_name='scorecard')
    op.drop_table('scorecard')
    op.drop_index(op.f('ix_microservicescorecard_id'), table_name='microservicescorecard')
    op.drop_table('microservicescorecard')
    op.drop_index(op.f('ix_metric_name'), table_name='metric')
    op.drop_index(op.f('ix_metric_id'), table_name='metric')
    op.drop_index(op.f('ix_metric_code'), table_name='metric')
    op.drop_table('metric')
    # ### end Alembic commands ###
