name: CI/CD Pipeline

on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: noraali/back_end_project:latest

      # - name: Build and Push Frontend Image
      #   uses: docker/build-push-action@v6
      #   with: #Dockerfile for reactApp
      #     push: true
      #     tags: noraali/front_end_project:latest

    #   - name: Build and Push Image
    #     uses: docker/build-push-action@v6
    #     with:
    #       push: true
    #       tags: noraali/microcentral:latest
