name: CI/CD Pipeline

on:
  push:
    branches:
      - CI-CD-pipline
    tags:
      - v*

env:
  IMAGE_TAG:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}
      
      - name: Extract the latest Git tag
        id: git_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $IMAGE_TAG    


      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/back_end_project:latest

      # - name: Build and Push Frontend Image
      #   uses: docker/build-push-action@v6
      #   with: #Dockerfile for reactApp
      #     push: true
      #     tags: noraali/front_end_project:latest

    #   - name: Build and Push Image
    #     uses: docker/build-push-action@v6
    #     with:
    #       push: true
    #       tags: noraali/microcentral:latest
