name: CI/CD Pipeline

on:
  push:
    # branches:
    #   - CI-CD-pipline
    #   - main-backend
    #   - main-frontend
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Extract the latest Git tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV 

      - name: Build and Push Backend Image
        if: github.ref == 'refs/heads/CI-CD-pipline' 
        # main-backend
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: noraali/backend:${{ env.TAG }}
          context: .
          file: ./Dockerfile

      # - name: Build and Push Frontend Image
      #   if: github.ref == 'refs/heads/CI-CD-pipline'
      #                                 #  main-frontend
      #   uses: docker/build-push-action@v6
      #   with: 
      #     push: true
      #     tags: noraali/front_end_project:${{ env.TAG }}
      #     context: ./templates  #frontend folder
          # file: ./templates/Dockerfile


